version: '3.7'

services:
  drive_mongodb:
    image: ${PLATFORM_DRIVE_MONGODB_DOCKER_IMAGE:?err}
    restart: unless-stopped
    volumes:
      - drive_mongodb_data:/data/db
      - ~/.mn/${CONFIG_NAME:?err}/initiate_mongodb_replica.js:/docker-entrypoint-initdb.d/initiate_mongodb_replica.js
    extra_hosts:
      - "drive_mongodb:127.0.0.1"
    command: mongod --replSet driveDocumentIndices --bind_ip_all

  drive_abci:
    image: ${PLATFORM_DRIVE_ABCI_DOCKER_IMAGE:?err}
    restart: unless-stopped
    depends_on:
      - drive_mongodb
      - core
    volumes:
      - drive_abci_leveldb:/usr/src/app/db
    environment:
      - ABCI_PORT=${PLATFORM_DRIVE_ABCI_PORT:?err}
      - CORE_JSON_RPC_USERNAME=${CORE_RPC_USER:?err}
      - CORE_JSON_RPC_PASSWORD=${CORE_RPC_PASSWORD:?err}
      - CORE_JSON_RPC_HOST=core
      - CORE_JSON_RPC_PORT=${CORE_RPC_PORT:?err}
      - DOCUMENT_MONGODB_URL=mongodb://drive_mongodb:${PLATFORM_DRIVE_MONGODB_PORT:?err}?replicaSet=driveDocumentIndices
      - DPNS_CONTRACT_ID=${PLATFORM_DPNS_CONTRACT_ID}
      - DPNS_TOP_LEVEL_IDENTITY=${PLATFORM_DPNS_OWNER_ID}
    command: npm run abci

  drive_tendermint:
    image: ${PLATFORM_DRIVE_TENDERMINT_DOCKER_IMAGE:?err}
    restart: unless-stopped
    depends_on:
      - drive_abci
    ports:
      - ${PLATFORM_DRIVE_TENDERMINT_P2P_PORT:?err}:${PLATFORM_DRIVE_TENDERMINT_P2P_PORT:?err} # P2P
    volumes:
      - ~/.mn/${CONFIG_NAME:?err}/genesis.json:/tendermint/config/genesis.json
      - ~/.mn/${CONFIG_NAME:?err}/config.toml:/tendermint/config/config.toml
      - drive_tendermint_homedir:/tendermint
    entrypoint: sh -c "/usr/bin/tendermint init && /usr/bin/tendermint node"

  dapi_insight:
    image: ${PLATFORM_DAPI_INSIGHT_DOCKER_IMAGE:?err}
    restart: unless-stopped
    depends_on:
      - core
    volumes:
      - ~/.mn/${CONFIG_NAME:?err}/dashcore-node.json:/insight/dashcore-node.json

  dapi_api:
    image: ${PLATFORM_DAPI_API_DOCKER_IMAGE:?err}
    restart: unless-stopped
    depends_on:
      - drive_tendermint
      - dapi_insight
      - core
    environment:
      - INSIGHT_URI=http://dapi_insight:${PLATFORM_DAPI_INSIGHT_PORT:?err}/insight-api
      - API_JSON_RPC_PORT=${PLATFORM_DAPI_API_JSON_RPC_PORT:?err}
      - API_GRPC_PORT=${PLATFORM_DAPI_API_GRPC_PORT:?err}
      - DASHCORE_RPC_HOST=core
      - DASHCORE_RPC_PORT=${CORE_RPC_PORT:?err}
      - DASHCORE_RPC_USER=${CORE_RPC_USER:?err}
      - DASHCORE_RPC_PASS=${CORE_RPC_PASSWORD:?err}
      - DASHCORE_ZMQ_HOST=core
      - DASHCORE_ZMQ_PORT=${CORE_ZMQ_PORT:?err}
      - DASHCORE_P2P_HOST=core
      - DASHCORE_P2P_PORT=${CORE_P2P_PORT:?err}
      - DASHCORE_P2P_NETWORK=devnet
      - NETWORK=devnet
      - TENDERMINT_RPC_HOST=drive_tendermint
      - TENDERMINT_RPC_PORT=${PLATFORM_DRIVE_TENDERMINT_RPC_PORT:?err}
    command: npm run api

  dapi_tx_filter_stream:
    image: ${PLATFORM_DAPI_API_DOCKER_IMAGE:?err}
    restart: unless-stopped
    depends_on:
      - core
      - dapi_insight
    environment:
      - INSIGHT_URI=http://dapi_insight:${PLATFORM_DAPI_INSIGHT_PORT:?err}/insight-api
      - TX_FILTER_STREAM_GRPC_PORT=${PLATFORM_DAPI_TX_FILTER_STREAM_PORT:?err}
      - DASHCORE_RPC_HOST=core
      - DASHCORE_RPC_PORT=${CORE_RPC_PORT:?err}
      - DASHCORE_RPC_USER=${CORE_RPC_USER:?err}
      - DASHCORE_RPC_PASS=${CORE_RPC_PASSWORD:?err}
      - DASHCORE_ZMQ_HOST=core
      - DASHCORE_ZMQ_PORT=${CORE_ZMQ_PORT:?err}
      - DASHCORE_P2P_HOST=core
      - DASHCORE_P2P_PORT=${CORE_P2P_PORT:?err}
      - DASHCORE_P2P_NETWORK=devnet
      - NETWORK=devnet
      - TENDERMINT_RPC_HOST=drive_tendermint
      - TENDERMINT_RPC_PORT=${PLATFORM_DRIVE_TENDERMINT_RPC_PORT:?err}
    command: npm run tx-filter-stream

  dapi_envoy:
    image: ${PLATFORM_DAPI_ENVOY_DOCKER_IMAGE:?err}
    restart: unless-stopped
    depends_on:
      - dapi_api
      - dapi_tx_filter_stream
    volumes:
      - ~/.mn/${CONFIG_NAME:?err}/grpc.yaml:/etc/envoy/envoy.yaml

  dapi_nginx:
    image: ${PLATFORM_DAPI_NGINX_DOCKER_IMAGE:?err}
    restart: unless-stopped
    depends_on:
      - dapi_api
      - dapi_tx_filter_stream
      - dapi_envoy
    ports:
      - 3000:80 # JSON RPC and gRPC Web
      - 3010:50051 # gRPC Native
    volumes:
      - ~/.mn/${CONFIG_NAME:?err}/default.conf:/etc/nginx/conf.d/default.conf
      - ~/.mn/${CONFIG_NAME:?err}/grpc.conf:/etc/nginx/conf.d/grpc.conf
      - ~/.mn/${CONFIG_NAME:?err}/errors.grpc_conf:/etc/nginx/conf.d/errors.grpc_conf

volumes:
  drive_abci_leveldb:
  drive_mongodb_data:
  drive_tendermint_homedir:
