version: '3'

services:
  core:
    image: dashpay/dashd:${DASHD_VERSION}
    container_name: core
    restart: always
    ports:
    - 20001:20001
    volumes:
      - ./configs/${PRESET}/core/dashd.conf:/dashd.conf
      - ./data/core:/data
    command: 'dashd -conf=/dashd.conf -datadir=/data -masternodeblsprivkey=${MASTERNODE_BLS_PRIV_KEY:?err} -externalip=${EXTERNAL_IP:?err}'

  dapi_insight:
    image: dashpay/insight-api
    container_name: dapi_insight
    restart: always
    volumes:
      - ./configs/${PRESET}/dapi-insight/dashcore-node.json:/insight/dashcore-node.json
    depends_on:
      - core

  drive_mongodb:
    image: mongo:4.2
    container_name: drive_mongodb
    command: mongod --replSet driveDocumentIndices --bind_ip_all
    volumes:
      - drive_mongodb:/data/db

  mongo_replica_init:
    image: mongo:4.2
    depends_on:
      - drive_mongodb
    volumes:
      - ./scripts:/deployment_scripts
    entrypoint:
      - /deployment_scripts/initiate_replica.sh

  drive_update_state:
    image: dashpay/drive:${DRIVE_VERSION}
    container_name: drive_update_state
    restart: always
    command: sh -c "sleep 10 && npm run updateState"
    environment:
      - DASHCORE_JSON_RPC_USER=dashrpc
      - DASHCORE_JSON_RPC_PASS=password
      - DASHCORE_JSON_RPC_HOST=core
      - DASHCORE_JSON_RPC_PORT=20002
      - STATEVIEW_MONGODB_URL=mongodb://drive_mongodb:27017
      - UPDATE_STATE_GRPC_PORT=5000
      - TENDERMINT_RPC_HOST=tendermint
      - TENDERMINT_RPC_PORT=26657
      - DPNS_CONTRACT_ID=${DPNS_CONTRACT_ID}
      - DPNS_TOP_LEVEL_IDENTITY=${DPNS_TOP_LEVEL_IDENTITY}
    depends_on:
      - mongo_replica_init

  drive_api:
    image: dashpay/drive:${DRIVE_VERSION}
    container_name: drive_api
    restart: always
    command: npm run api
    environment:
      - DASHCORE_JSON_RPC_USER=dashrpc
      - DASHCORE_JSON_RPC_PASS=password
      - DASHCORE_JSON_RPC_HOST=core
      - DASHCORE_JSON_RPC_PORT=20002
      - STATEVIEW_MONGODB_URL=mongodb://drive_mongodb:27017
      - API_RPC_PORT=6000
      - TENDERMINT_RPC_HOST=tendermint
      - TENDERMINT_RPC_PORT=26657
    depends_on:
      - mongo_replica_init
      - core

  machine:
    image: dashpay/js-machine:${MACHINE_VERSION}
    container_name: machine
    command: npm run abci
    environment:
      - DRIVE_UPDATE_STATE_HOST=drive_update_state
      - DRIVE_UPDATE_STATE_PORT=5000
      - DRIVE_API_HOST=drive_api
      - DRIVE_API_PORT=6000
      - RATE_LIMITER_ACTIVE=false
      - RATE_LIMITER_MAX_TRANSITIONS_PER_ID=100
      - RATE_LIMITER_PER_BLOCK_INTERVAL=36
      - RATE_LIMITER_PER_BAN_INTERVAL=17280
      - RATE_LIMITER_INTERVAL_PREFIX='ratelimiter.interval'
      - RATE_LIMITER_BAN_PREFIX='ratelimiter.ban'
    volumes:
      - machine_leveldb:/usr/src/app/db
    depends_on:
      - drive_api
      - drive_update_state

  tendermint:
    image: tendermint/tendermint:v0.32.8
    container_name: tendermint
    entrypoint: sh -c "sleep 30 && /usr/bin/tendermint init && /usr/bin/tendermint node"
    restart: always
    ports:
      - 26656:26656
    volumes:
      - ./configs/${PRESET}/tendermint:/tendermint
      - ./data/tendermint:/data
    depends_on:
      - machine

  dapi_api:
    image: dashpay/dapi:${DAPI_VERSION}
    container_name: dapi_api
    command: npm run api
    restart: always
    depends_on:
      - tendermint
    environment:
      - INSIGHT_URI=http://dapi_insight:3001/dapi_insight-api
      - API_JSON_RPC_PORT=3004
      - API_GRPC_PORT=3005
      - DASHCORE_RPC_HOST=core
      - DASHCORE_RPC_PORT=20002
      - DASHCORE_RPC_USER=dashrpc
      - DASHCORE_RPC_PASS=password
      - DASHCORE_ZMQ_HOST=core
      - DASHCORE_ZMQ_PORT=29998
      - DASHCORE_P2P_HOST=core
      - DASHCORE_P2P_PORT=20001
      - DASHCORE_P2P_NETWORK=devnet
      - DRIVE_RPC_HOST=drive_api
      - DRIVE_RPC_PORT=6000
      - NETWORK=devnet
      - TENDERMINT_CORE_HOST=tendermint
      - TENDERMINT_CORE_PORT=26657

  dapi_tx_filter_stream:
    image: dashpay/dapi:${DAPI_VERSION}
    container_name: dapi_tx_filter_stream
    command: npm run tx-filter-stream
    restart: always
    environment:
      - INSIGHT_URI=http://dapi_insight:3001/dapi_insight-api
      - TX_FILTER_STREAM_GRPC_PORT=3006
      - DASHCORE_RPC_HOST=core
      - DASHCORE_RPC_PORT=20002
      - DASHCORE_RPC_USER=dashrpc
      - DASHCORE_RPC_PASS=password
      - DASHCORE_ZMQ_HOST=core
      - DASHCORE_ZMQ_PORT=29998
      - DASHCORE_P2P_HOST=core
      - DASHCORE_P2P_PORT=20001
      - DASHCORE_P2P_NETWORK=devnet
      - DRIVE_RPC_HOST=drive_api
      - DRIVE_RPC_PORT=6000
      - NETWORK=devnet
    depends_on:
      - drive_api

  dapi_nginx:
    image: nginx:latest
    container_name: dapi_nginx
    depends_on:
      - dapi_api
      - dapi_tx_filter_stream
      - dapi_insight
    ports:
      - 3000:80
      - 3010:50051
      - 3001:3001
    volumes:
      - ./configs/${PRESET}/dapi-nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./configs/${PRESET}/dapi-nginx/grpc.conf:/etc/nginx/conf.d/grpc.conf
      - ./configs/${PRESET}/dapi-nginx/errors.grpc_conf:/etc/nginx/conf.d/errors.grpc_conf
      - ./configs/${PRESET}/dapi-nginx/insight.conf:/etc/nginx/conf.d/insight.conf

  dapi_envoy:
    image: envoyproxy/envoy:latest
    container_name: dapi_envoy
    depends_on:
      - dapi_api
    volumes:
      - ./configs/${PRESET}/envoy/grpc.yaml:/etc/envoy/envoy.yaml
    restart: always

volumes:
  drive_mongodb:
  machine_leveldb:
