# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# NOTE: Any path below can be absolute (e.g. "/var/myawesomeapp/data") or
# relative to the home directory (e.g. "data"). The home directory is
# "$HOME/.tendermint" by default, but could be changed via $TMHOME env variable
# or --home cmd flag.

##### main base config options #####

# TCP or UNIX socket address of the ABCI application,
# or the name of an ABCI application compiled in with the Tendermint binary
proxy_app = "tcp://drive_abci:26658"

# A custom human readable name for this node
#moniker = ""

# If this node is many blocks behind the tip of the chain, FastSync
# allows them to catchup quickly by downloading blocks in parallel
# and verifying their commits
fast_sync = true

# Database backend: goleveldb | cleveldb | boltdb
# * goleveldb (github.com/syndtr/goleveldb - most popular implementation)
#   - pure go
#   - stable
# * cleveldb (uses levigo wrapper)
#   - fast
#   - requires gcc
#   - use cleveldb build tag (go build -tags cleveldb)
# * boltdb (uses etcd's fork of bolt - github.com/etcd-io/bbolt)
#   - EXPERIMENTAL
#   - may be faster is some use-cases (random reads - indexer)
#   - use boltdb build tag (go build -tags boltdb)
db_backend = "goleveldb"

# Database directory
db_dir = "/data/db"

# Output level for logging, including package level options
log_level = "main:info,state:info,*:error"
#log_level = "*:debug"

# Output format: 'plain' (colored text) or 'json'
log_format = "plain"

##### additional base config options #####

# Path to the JSON file containing the initial validator set and other meta data
genesis_file = "config/genesis.json"

# Path to the JSON file containing the private key to use as a validator in the consensus protocol
priv_validator_key_file = "/data/priv_validator_key.json"

# Path to the JSON file containing the last sign state of a validator
priv_validator_state_file = "/data/priv_validator_state.json"

# TCP or UNIX socket address for Tendermint to listen on for
# connections from an external PrivValidator process
priv_validator_laddr = ""

# Path to the JSON file containing the private key to use for node authentication in the p2p protocol
node_key_file = "/data/node_key.json"

# Mechanism to connect to the ABCI application: socket | grpc
abci = "socket"

# TCP or UNIX socket address for the profiling server to listen on
prof_laddr = ""

# If true, query the ABCI app on connecting to a new peer
# so the app can decide if we should keep the connection or not
filter_peers = false

##### advanced configuration options #####

##### rpc server configuration options #####
[rpc]

# TCP or UNIX socket address for the RPC server to listen on
laddr = "tcp://0.0.0.0:26657"

# A list of origins a cross-domain request can be executed from
# Default value '[]' disables cors support
# Use '["*"]' to allow any origin
cors_allowed_origins = []

# A list of methods the client is allowed to use with cross-domain requests
cors_allowed_methods = ["HEAD", "GET", "POST", ]

# A list of non simple headers the client is allowed to use with cross-domain requests
cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time", ]

# TCP or UNIX socket address for the gRPC server to listen on
# NOTE: This server only supports /broadcast_tx_commit
grpc_laddr = ""

# Maximum number of simultaneous connections.
# Does not include RPC (HTTP&WebSocket) connections. See max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
grpc_max_open_connections = 900

# Activate unsafe RPC commands like /dial_seeds and /unsafe_flush_mempool
unsafe = false

# Maximum number of simultaneous connections (including WebSocket).
# Does not include gRPC connections. See grpc_max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
max_open_connections = 900

# Maximum number of unique clientIDs that can /subscribe
# If you're using /broadcast_tx_commit, set to the estimated maximum number
# of broadcast_tx_commit calls per block.
max_subscription_clients = 100

# Maximum number of unique queries a given client can /subscribe to
# If you're using GRPC (or Local RPC client) and /broadcast_tx_commit, set to
# the estimated # maximum number of broadcast_tx_commit calls per block.
max_subscriptions_per_client = 5

# How long to wait for a tx to be committed during /broadcast_tx_commit.
# WARNING: Using a value larger than 10s will result in increasing the
# global HTTP write timeout, which applies to all connections and endpoints.
# See https://github.com/tendermint/tendermint/issues/3435
timeout_broadcast_tx_commit = "10s"

# Maximum size of request body, in bytes
max_body_bytes = 1000000

# Maximum size of request header, in bytes
max_header_bytes = 1048576

# The path to a file containing certificate that is used to create the HTTPS server.
# Migth be either absolute path or path related to tendermint's config directory.
# If the certificate is signed by a certificate authority,
# the certFile should be the concatenation of the server's certificate, any intermediates,
# and the CA's certificate.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server.
# Otherwise, HTTP server is run.
tls_cert_file = ""

# The path to a file containing matching private key that is used to create the HTTPS server.
# Migth be either absolute path or path related to tendermint's config directory.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server.
# Otherwise, HTTP server is run.
tls_key_file = ""

##### peer to peer configuration options #####
[p2p]

# Address to listen for incoming connections
laddr = "tcp://0.0.0.0:26656"

# Address to advertise to peers for them to dial
# If empty, will use the same port as the laddr,
# and will introspect on the listener or use UPnP
# to figure out the address.
#external_address = ""

# Comma separated list of seed nodes to connect to
seeds = ""

# Comma separated list of nodes to keep persistent connections to
persistent_peers = "f94e4e15dba201fbc756baa571b09bf7d0612e24@52.89.124.211:26656,eca2004a2070f4591eb574cde8f28309978bd974@34.209.193.190:26656,d8e0ed835f86285709a2eeef7b9360f8f695942e@35.166.6.110:26656,43d81dbf85d807e9039e0420df6a60f7f4ec3433@34.221.28.0:26656,4fb5749a483653d52e57fe5c3ebf252aeed5ea07@54.203.118.246:26656,1a0e91abd779f16ed862c3d9856242651407b7a0@35.162.228.3:26656,7521afd665df8e83c37b0332274686ccbb97dea0@54.202.168.30:26656,c82aaccabd7a1dc001e9d68b7e0be92b884db493@52.33.172.246:26656,40e46c6ff071115bda544f2a539d1b59a870f4b1@52.10.63.195:26656,0044c0baa73d2ec77d42369360e7678f5305de34@34.220.63.84:26656,437d1a0f9efb226176581794643443ee9dfa8f85@35.167.48.167:26656,522a27ee8403791fb3e66fca30ed82d6845145f6@54.212.9.170:26656,fd2c1e175b5933272d130af6bf21dc13b58a689c@34.220.78.165:26656,95391bdf8f89f16a2ea6b51d333cf0a525e3046e@54.187.122.146:26656,e1ac03865c2aeea53cb43dd6518cedb9fb0edb78@50.112.197.142:26656,0da909b00e42b54e14da28959c1f17d959bd32af@34.219.251.242:26656,bccff8286a55efa4e423a790f7141aae0ae6ba26@34.216.14.190:26656,b9d9c48501ca07552e325814c5d2df29c2e18fe1@34.222.50.204:26656,0c4bd3657bd0c92a21f1f2127e9930c16296386f@34.221.137.203:26656,47031dde3e60af1cf690a88c7743438142823d37@52.24.144.3:26656,48f009a0c1ea8348a33bac86fc9bbc5076254d0b@18.236.165.125:26656,f419582dc59965b906f02dd4426d6ea2df7a7bb4@54.188.167.159:26656,c9cd479ac93660b49c20ea16cf78de9309a28d6c@54.201.41.131:26656,0e5c92ed1181d30a6b4666474411c9923e593211@34.219.137.212:26656,e1012db054f5faba29f0fa94a34da0d0b1dcf331@34.220.50.187:26656,da11d1e40f85f5c36dfc66f27d151763acad9e53@54.202.66.234:26656,1715533eab2b238fca68010eda720f88ac114164@34.209.42.117:26656,497861871a47950ed3d404047c9c5e9662321772@34.217.19.154:26656,77d7eee9c24c935731750a17638c754c17698d56@34.214.193.163:26656,a227a11cd2e6785184f26f49c310abafab0ddafa@54.191.242.14:26656,5aeaebc01319e7176efa70c7ba539e561af466f2@18.236.198.228:26656,96c5d6e7ab29833e066575f4521cc1f11dfa06e8@34.212.176.135:26656,79249f225f57b642e88d1bb80bac2a537408e66f@52.13.98.99:26656,b8bef7814c70f8891e9af5b4c2931a7ca92bbfb8@52.26.203.151:26656,aa54e1a47dcb142ecae302c0103bbfc1351e9641@52.12.32.108:26656,94095d3c1106f371172e8ed5e90e5f3ce63e36c4@52.43.56.134:26656,0e4b0fccc1ed6f9023a08693e85dd99f07b1dc11@52.36.222.114:26656,7500d8876bad7f713dfa738ce89de17d925a77af@34.221.146.34:26656,a2403f992fc2d8e0e281ab13d7c562e1fcbd46e3@34.219.128.5:26656,3700ddcc92eb62575a22e790d64b04add178bf31@54.213.244.91:26656,290c61467c66d078605f9fa952bba9a1c068b63c@34.221.55.32:26656,f68714dc89a1a864ddbf2624a2174ff1e611e095@18.237.78.167:26656,7a98ae92b732c63636a668ec367eeac038d01fb3@54.214.164.230:26656,58919c4d6229523bf5581ddc3419a29b2f280abc@35.167.1.167:26656,6b6c1890c7e24b4bac6c0fb349d018d103d5de65@54.245.150.218:26656,6e63a77629b7325a580756420409a7e650adf532@34.222.243.95:26656,70a3fc898eb818e9845828b47fd80dd08ba60dcf@54.190.26.164:26656,98562d699256ea9faa966d187d99023dc493bf41@34.222.46.203:26656,dc3bec8b13ffc57070d897bc0e1d6735efa4534d@34.218.66.230:26656"

# UPNP port forwarding
upnp = false

# Path to address book
addr_book_file = "/data/addrbook.json"

# Set true for strict address routability rules
# Set false for private or local networks
addr_book_strict = true

# Maximum number of inbound peers
max_num_inbound_peers = 40

# Maximum number of outbound peers to connect to, excluding persistent peers
max_num_outbound_peers = 10

# Time to wait before flushing messages out on the connection
flush_throttle_timeout = "100ms"

# Maximum size of a message packet payload, in bytes
max_packet_msg_payload_size = 1024

# Rate at which packets can be sent, in bytes/second
send_rate = 5120000

# Rate at which packets can be received, in bytes/second
recv_rate = 5120000

# Set true to enable the peer-exchange reactor
pex = true

# Seed mode, in which node constantly crawls the network and looks for
# peers. If another node asks it for addresses, it responds and disconnects.
#
# Does not work if the peer-exchange reactor is disabled.
seed_mode = false

# Comma separated list of peer IDs to keep private (will not be gossiped to other peers)
private_peer_ids = ""

# Toggle to disable guard against peers connecting from the same ip.
allow_duplicate_ip = false

# Peer connection configuration.
handshake_timeout = "20s"
dial_timeout = "3s"

##### mempool configuration options #####
[mempool]

recheck = true
broadcast = true
wal_dir = ""

# Maximum number of transactions in the mempool
size = 5000

# Limit the total size of all txs in the mempool.
# This only accounts for raw transactions (e.g. given 1MB transactions and
# max_txs_bytes=5MB, mempool will only accept 5 transactions).
max_txs_bytes = 1073741824

# Size of the cache (used to filter transactions we saw earlier) in transactions
cache_size = 10000

# Maximum size of a single transaction.
# NOTE: the max size of a tx transmitted over the network is {max_tx_bytes} + {amino overhead}.
max_tx_bytes = 1048576

##### fast sync configuration options #####
[fastsync]

# Fast Sync version to use:
#   1) "v0" (default) - the legacy fast sync implementation
#   2) "v1" - refactor of v0 version for better testability
version = "v0"

##### consensus configuration options #####
[consensus]

wal_file = "/data/db/cs.wal/wal"

timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "5s"

# Make progress as soon as we have all the precommits (as if TimeoutCommit = 0)
skip_timeout_commit = false

# EmptyBlocks mode and possible interval between empty blocks
create_empty_blocks = false
create_empty_blocks_interval = "0s"

# Reactor sleep duration parameters
peer_gossip_sleep_duration = "100ms"
peer_query_maj23_sleep_duration = "2s"

##### transactions indexer configuration options #####
[tx_index]

# What indexer to use for transactions
#
# Options:
#   1) "null"
#   2) "kv" (default) - the simplest possible indexer, backed by key-value storage (defaults to levelDB; see DBBackend).
indexer = "kv"

# Comma-separated list of tags to index (by default the only tag is "tx.hash")
#
# You can also index transactions by height by adding "tx.height" tag here.
#
# It's recommended to index only a subset of tags due to possible memory
# bloat. This is, of course, depends on the indexer's DB and the volume of
# transactions.
index_tags = ""

# When set to true, tells indexer to index all tags (predefined tags:
# "tx.hash", "tx.height" and all tags from DeliverTx responses).
#
# Note this may be not desirable (see the comment above). IndexTags has a
# precedence over IndexAllTags (i.e. when given both, IndexTags will be
# indexed).
index_all_tags = true

##### instrumentation configuration options #####
[instrumentation]

# When true, Prometheus metrics are served under /metrics on
# PrometheusListenAddr.
# Check out the documentation for the list of available metrics.
prometheus = false

# Address to listen for Prometheus collector(s) connections
prometheus_listen_addr = ":26660"

# Maximum number of simultaneous connections.
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
max_open_connections = 3

# Instrumentation namespace
namespace = "drive_tendermint"
