# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# NOTE: Any path below can be absolute (e.g. "/var/myawesomeapp/data") or
# relative to the home directory (e.g. "data"). The home directory is
# "$HOME/.tendermint" by default, but could be changed via $TMHOME env variable
# or --home cmd flag.

##### main base config options #####

# TCP or UNIX socket address of the ABCI application,
# or the name of an ABCI application compiled in with the Tendermint binary
proxy_app = "tcp://drive_abci:26658"

# A custom human readable name for this node
#moniker = ""

# If this node is many blocks behind the tip of the chain, FastSync
# allows them to catchup quickly by downloading blocks in parallel
# and verifying their commits
fast_sync = true

# Database backend: goleveldb | cleveldb | boltdb
# * goleveldb (github.com/syndtr/goleveldb - most popular implementation)
#   - pure go
#   - stable
# * cleveldb (uses levigo wrapper)
#   - fast
#   - requires gcc
#   - use cleveldb build tag (go build -tags cleveldb)
# * boltdb (uses etcd's fork of bolt - github.com/etcd-io/bbolt)
#   - EXPERIMENTAL
#   - may be faster is some use-cases (random reads - indexer)
#   - use boltdb build tag (go build -tags boltdb)
db_backend = "goleveldb"

# Database directory
db_dir = "/data/db"

# Output level for logging, including package level options
log_level = "main:info,state:info,*:error"
#log_level = "*:debug"

# Output format: 'plain' (colored text) or 'json'
log_format = "plain"

##### additional base config options #####

# Path to the JSON file containing the initial validator set and other meta data
genesis_file = "config/genesis.json"

# Path to the JSON file containing the private key to use as a validator in the consensus protocol
priv_validator_key_file = "/data/priv_validator_key.json"

# Path to the JSON file containing the last sign state of a validator
priv_validator_state_file = "/data/priv_validator_state.json"

# TCP or UNIX socket address for Tendermint to listen on for
# connections from an external PrivValidator process
priv_validator_laddr = ""

# Path to the JSON file containing the private key to use for node authentication in the p2p protocol
node_key_file = "/data/node_key.json"

# Mechanism to connect to the ABCI application: socket | grpc
abci = "socket"

# TCP or UNIX socket address for the profiling server to listen on
prof_laddr = ""

# If true, query the ABCI app on connecting to a new peer
# so the app can decide if we should keep the connection or not
filter_peers = false

##### advanced configuration options #####

##### rpc server configuration options #####
[rpc]

# TCP or UNIX socket address for the RPC server to listen on
laddr = "tcp://0.0.0.0:26657"

# A list of origins a cross-domain request can be executed from
# Default value '[]' disables cors support
# Use '["*"]' to allow any origin
cors_allowed_origins = []

# A list of methods the client is allowed to use with cross-domain requests
cors_allowed_methods = ["HEAD", "GET", "POST", ]

# A list of non simple headers the client is allowed to use with cross-domain requests
cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time", ]

# TCP or UNIX socket address for the gRPC server to listen on
# NOTE: This server only supports /broadcast_tx_commit
grpc_laddr = ""

# Maximum number of simultaneous connections.
# Does not include RPC (HTTP&WebSocket) connections. See max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
grpc_max_open_connections = 900

# Activate unsafe RPC commands like /dial_seeds and /unsafe_flush_mempool
unsafe = false

# Maximum number of simultaneous connections (including WebSocket).
# Does not include gRPC connections. See grpc_max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
max_open_connections = 900

# Maximum number of unique clientIDs that can /subscribe
# If you're using /broadcast_tx_commit, set to the estimated maximum number
# of broadcast_tx_commit calls per block.
max_subscription_clients = 100

# Maximum number of unique queries a given client can /subscribe to
# If you're using GRPC (or Local RPC client) and /broadcast_tx_commit, set to
# the estimated # maximum number of broadcast_tx_commit calls per block.
max_subscriptions_per_client = 5

# How long to wait for a tx to be committed during /broadcast_tx_commit.
# WARNING: Using a value larger than 10s will result in increasing the
# global HTTP write timeout, which applies to all connections and endpoints.
# See https://github.com/tendermint/tendermint/issues/3435
timeout_broadcast_tx_commit = "10s"

# Maximum size of request body, in bytes
max_body_bytes = 1000000

# Maximum size of request header, in bytes
max_header_bytes = 1048576

# The path to a file containing certificate that is used to create the HTTPS server.
# Migth be either absolute path or path related to tendermint's config directory.
# If the certificate is signed by a certificate authority,
# the certFile should be the concatenation of the server's certificate, any intermediates,
# and the CA's certificate.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server.
# Otherwise, HTTP server is run.
tls_cert_file = ""

# The path to a file containing matching private key that is used to create the HTTPS server.
# Migth be either absolute path or path related to tendermint's config directory.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server.
# Otherwise, HTTP server is run.
tls_key_file = ""

##### peer to peer configuration options #####
[p2p]

# Address to listen for incoming connections
laddr = "tcp://0.0.0.0:26656"

# Address to advertise to peers for them to dial
# If empty, will use the same port as the laddr,
# and will introspect on the listener or use UPnP
# to figure out the address.
#external_address = ""

# Comma separated list of seed nodes to connect to
seeds = ""

# Comma separated list of nodes to keep persistent connections to
persistent_peers = "8a5a4d5712d6a919c0528aeef0dc59304628d5fb@52.89.124.211:26656,9099880545d7dc3dfa1d475f6aef0dba075b46d9@34.209.193.190:26656,3ffe3881154fac2eac00912cd5f4be9e516cbad9@35.166.6.110:26656,4bf7eace91f568a5c8a1efceddd183270e494912@34.221.28.0:26656,3d5f069805aa255858a1e9dbe3a35c1f6c197752@54.203.118.246:26656,976a5c0e1236eff999596ffa728be9f1d7a1c359@35.162.228.3:26656,0379da85cbfc71d460db558ea11ee70e779bccd5@54.202.168.30:26656,7d322d32085d91bef02a1f8853102eecaedcd301@52.33.172.246:26656,5be2ca5461808761d6a84018075f0d3f1ea6cfb0@52.10.63.195:26656,c2209cdaf9e58179e7d3ea646d2f7a9510853042@34.220.63.84:26656,c0df04849f96853b67f68addbb240ded8005aa62@35.167.48.167:26656,1233a3e6bcc5a40e455fb77f7a92d0ae8cdbcc60@54.212.9.170:26656,6f3286991f0c43f15e0115e0981aa4bbb9676859@34.220.78.165:26656,29ab6d97a0be4021b3e9a35607881b9f2f0092ad@54.187.122.146:26656,df331b81076533e23e3ae400129ed6ad0f1f7098@50.112.197.142:26656,a64959684f3f4731227bd15ede5de1cf1cbb4f61@34.219.251.242:26656,4b5110b1d5e81c291bac63e040f147dcd08d28f4@34.216.14.190:26656,5a2792777b90290dbd6b0486d723411561713a44@34.222.50.204:26656,e7e617c41fee95c63c4856059891a3349dc4e05a@34.221.137.203:26656,8fedf0cf2a9c52a68d23cf68df89497fb191d732@52.24.144.3:26656,27980ff03be4ace7f0e52b98be7f0c4a1f74cf79@18.236.165.125:26656,8d3cddbb79d1aa054123e99f9862e0e92dff6d93@54.188.167.159:26656,a3de558fe2d6743e4129314e3ef897c1cb489942@54.201.41.131:26656,950c1a1f5d3be5f7b25079688522827406b39024@34.219.137.212:26656,783fcb442377cd5b88349b811c25cf034fe70cda@34.220.50.187:26656,7a585f04ad632167e5cd28f346150e056b0e0ac5@54.202.66.234:26656,0a89137631c10be8d77b3d6924b98ef2435f0ef0@34.209.42.117:26656,870635e69ff4fa86ee120dae950e25d77861d2eb@34.217.19.154:26656,b64f211e596b7dc48428aa0b95d51f3994b8a30a@34.214.193.163:26656,16643e38d3c41625d9a20977c039f028064eb89a@54.191.242.14:26656,4b2f432eae87f19d0872564de8ce7328643abacb@18.236.198.228:26656,3ba1a8c41637afdd582aece2dd5f7f4829b22597@34.212.176.135:26656,4ed993461b1db3bb0191a352428c544db371ed1d@52.13.98.99:26656,cc22d25d5fdfb15af6d1ec086960b67500690f43@52.26.203.151:26656,b469ad4683a1ea174bd39c94ddd56715e9b1feae@52.12.32.108:26656,14011accfae4e8662ec61aca7b45c9562c025cdb@52.43.56.134:26656,10dfaa33fa4acbcb95ce51424b643976481bed11@52.36.222.114:26656,02953e529016a2307b15e8cb6d99f15e750bcaa1@34.221.146.34:26656,46251895f90a9878823190de61c09ab0656acafc@34.219.128.5:26656,41a719a7343c5031b550c4fb51cf5fde77800ccb@54.213.244.91:26656,c660b54480761472b7e16a83453d1c1d80b98405@34.221.55.32:26656,8af7c480f1b3b3faacb7a2cf0929aa2b8aa4f938@18.237.78.167:26656,24af3eee31ebfb8b45107355efff348f79d162a8@54.214.164.230:26656,fda763cb8514f8a3c19c6777239d4436115589fd@35.167.1.167:26656,3e256986f1058f25a178d73ae37c4a158a879c5b@54.245.150.218:26656,448592182af5d2c1504ba6ed108f1910d6c0adc2@34.222.243.95:26656,c18ae3a0610aeef329e5c2408bfa9865d2cec7fb@54.190.26.164:26656,4296121f0dd9eae6d3af70b448f62a1e59d8d870@34.222.46.203:26656,cecacef548c21bcc110f37a1412f4f788592cdb2@34.218.66.230:26656"

# UPNP port forwarding
upnp = false

# Path to address book
addr_book_file = "/data/addrbook.json"

# Set true for strict address routability rules
# Set false for private or local networks
addr_book_strict = true

# Maximum number of inbound peers
max_num_inbound_peers = 40

# Maximum number of outbound peers to connect to, excluding persistent peers
max_num_outbound_peers = 10

# Time to wait before flushing messages out on the connection
flush_throttle_timeout = "100ms"

# Maximum size of a message packet payload, in bytes
max_packet_msg_payload_size = 1024

# Rate at which packets can be sent, in bytes/second
send_rate = 5120000

# Rate at which packets can be received, in bytes/second
recv_rate = 5120000

# Set true to enable the peer-exchange reactor
pex = true

# Seed mode, in which node constantly crawls the network and looks for
# peers. If another node asks it for addresses, it responds and disconnects.
#
# Does not work if the peer-exchange reactor is disabled.
seed_mode = false

# Comma separated list of peer IDs to keep private (will not be gossiped to other peers)
private_peer_ids = ""

# Toggle to disable guard against peers connecting from the same ip.
allow_duplicate_ip = false

# Peer connection configuration.
handshake_timeout = "20s"
dial_timeout = "3s"

##### mempool configuration options #####
[mempool]

recheck = true
broadcast = true
wal_dir = ""

# Maximum number of transactions in the mempool
size = 5000

# Limit the total size of all txs in the mempool.
# This only accounts for raw transactions (e.g. given 1MB transactions and
# max_txs_bytes=5MB, mempool will only accept 5 transactions).
max_txs_bytes = 1073741824

# Size of the cache (used to filter transactions we saw earlier) in transactions
cache_size = 10000

# Maximum size of a single transaction.
# NOTE: the max size of a tx transmitted over the network is {max_tx_bytes} + {amino overhead}.
max_tx_bytes = 1048576

##### fast sync configuration options #####
[fastsync]

# Fast Sync version to use:
#   1) "v0" (default) - the legacy fast sync implementation
#   2) "v1" - refactor of v0 version for better testability
version = "v0"

##### consensus configuration options #####
[consensus]

wal_file = "/data/db/cs.wal/wal"

timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "5s"

# Make progress as soon as we have all the precommits (as if TimeoutCommit = 0)
skip_timeout_commit = false

# EmptyBlocks mode and possible interval between empty blocks
create_empty_blocks = false
create_empty_blocks_interval = "0s"

# Reactor sleep duration parameters
peer_gossip_sleep_duration = "100ms"
peer_query_maj23_sleep_duration = "2s"

##### transactions indexer configuration options #####
[tx_index]

# What indexer to use for transactions
#
# Options:
#   1) "null"
#   2) "kv" (default) - the simplest possible indexer, backed by key-value storage (defaults to levelDB; see DBBackend).
indexer = "kv"

# Comma-separated list of tags to index (by default the only tag is "tx.hash")
#
# You can also index transactions by height by adding "tx.height" tag here.
#
# It's recommended to index only a subset of tags due to possible memory
# bloat. This is, of course, depends on the indexer's DB and the volume of
# transactions.
index_tags = ""

# When set to true, tells indexer to index all tags (predefined tags:
# "tx.hash", "tx.height" and all tags from DeliverTx responses).
#
# Note this may be not desirable (see the comment above). IndexTags has a
# precedence over IndexAllTags (i.e. when given both, IndexTags will be
# indexed).
index_all_tags = true

##### instrumentation configuration options #####
[instrumentation]

# When true, Prometheus metrics are served under /metrics on
# PrometheusListenAddr.
# Check out the documentation for the list of available metrics.
prometheus = false

# Address to listen for Prometheus collector(s) connections
prometheus_listen_addr = ":26660"

# Maximum number of simultaneous connections.
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
max_open_connections = 3

# Instrumentation namespace
namespace = "drive_tendermint"
